travis:
  secure:
    BINSTAR_TOKEN: ITxWERWD4zer/KuZddfZiu9xzIMTIHEoYxEoUQyMIzOXwtBTCX++SAlRSus0derxgRrHplTqfGyQuNTPSb3enMLljPb4LwxkisDdt59rs3GeJdmV9OkgJBwuVV2RqQ5ND3ROSGXUc7bJCUYdqdHklQQhbz50Jvjr4/EDC42BwQ1M3FrXa3rIbdZ5qnMGyDvRxtAUiBj8vXdyWxvInGLLJoTweONhfD+H8FQ/Mxhnbc7HDf7XvhlAD6RWiKRTpjKzBdWH1m5eht6g5e9LvBTx5u7tvouddA+jM7E5QkPirFlfa/nqvtiQcBpItWJmp3OqkETFpA6iyntGTht4L2RChMVCYKK02qTbzDwNDFg9Lruh8A1W53a0YnDi4ZTNqwQEVFXj9RzyKSbevTTwxaMkmy9ManI8k50MQ2wKnkGxeVkr2jgkUx7GvWotOobUKvf4DctiVy1+i44hVE5wvt2E+N7N4RudMm+y/vnhnDZ2NOmw5wJ1MQf3WUcNXJlJw1uwLsVaE7kqZvLV4iOh501gD2q1c41sIh8sl+tG6zgZINvlgozh3cHmp6spe6NDSMUEYQV9YEGsLUuE/Eh8zg1mAmEEc5nBOl9ele6DCXanZBqC7VzZs29G0q8bpXfZ+237D2UxAZ8Fb2qgAd+CexvCDFivmLo3i9xFmBCVEV/ejfc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
